### ISSUE TITLE
New Version 2.1.1 Doesn't Support Laravel 6 on PHP 7.4.30

### ISSUE THREAD

**Issue by arif98741** [sujancse/php-csv-exporter#4]
Thanks for updating the package for laravel 9. 
But  after doing this is no longer supported in laravel 6 based on php 7.4; 

![image](https://user-images.githubusercontent.com/17213478/198937875-a2041dc1-a5ec-4902-8d90-f740a1251a37.png)

**Comment by arif98741** [comment]
I added a [pull request](https://github.com/sujancse/php-csv-exporter/pull/5) for fixing this issue. Please review and merge it.

**Comment by sujancse** [comment]
The issue has been solved on version `v2.1.2` which is the latest version. Thanks for pointing out the issue.
